# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-06 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_providerspeciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerspeciality',
            name='taxonomy_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
