# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-06 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_providerspeciality_taxonomy_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerspeciality',
            name='mappings',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
