# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-20 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0004_auto_20200306_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroupattributes',
            name='lower_limit_mapping',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agegroupattributes',
            name='upper_limit_mapping',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
