# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-06-17 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0005_auto_20200320_0152'),
        ('attributes', '0005_auto_20200320_0052'),
    ]

    operations = [
    ]
